// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    // Test name: Untitled
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.google.com/")
    // 2 | setWindowSize | 1578x1032 | 
    await driver.manage().window().setRect({ width: 1578, height: 1032 })
    // 3 | click | id=APjFqb | 
    await driver.findElement(By.id("APjFqb")).click()
    // 4 | type | id=APjFqb | abcdefg
    await driver.findElement(By.id("APjFqb")).sendKeys("abcdefg")
    // 5 | runScript | window.scrollTo(0,1023) | 
    await driver.executeScript("window.scrollTo(0,1023)")
    // 6 | click | css=.S8ee5 | 
    await driver.findElement(By.css(".S8ee5")).click()
  })
})
